name: CI - Absolute Realms Hierarchy

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/absolute-realms-submodule/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/absolute-realms-submodule/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'pnpm'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build
      run: pnpm --filter absolute-realms-submodule build
      
    - name: Lint
      run: pnpm --filter absolute-realms-submodule lint
      
    - name: Test
      run: pnpm --filter absolute-realms-submodule test