name: Nightly Quota Refresh

on:
  schedule:
    - cron: "0 2 * * *" # Runs every day at 2:00 AM UTC

jobs:
  refresh-quotas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: pnpm install

      - name: Generate YAML mapping
        run: pnpm workspace orchestrator-engine generate-mapping

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/orchestrator-engine/data/quotas/live-quotas.yaml
          git commit -m "Nightly quota refresh: Update live-quotas.yaml" || echo "No changes to commit"
          git push

      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Nightly Quota Refresh Failed"
          to: "maintainers@example.com"
          body: "The nightly quota refresh workflow has failed. Please check the logs for details."